//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("COM3D2.CustomEventLoader.Plugin.Resx.TextResource", typeof(TextResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Vagina&quot;: {
        ///    &quot;Slotname&quot;: &quot;body&quot;,
        ///    &quot;Part&quot;: &quot;Hibu&quot;,
        ///    &quot;MatNo&quot;: 0,
        ///    &quot;PropName&quot;: [
        ///      &quot;_MainTex&quot;,
        ///      &quot;_ShadowTex&quot;
        ///    ],
        ///    &quot;LayerNo&quot;: 15,
        ///    &quot;FileNameRaw&quot;: [
        ///      &quot;Rou/rou001:Rou/rou002:Rou/rou003:Rou/rou004:Rou/rou005&quot;,
        ///      &quot;Rou/rou001:Rou/rou002:Rou/rou003:Rou/rou004:Rou/rou005&quot;,
        ///      &quot;Rou/rou001:Rou/rou002:Rou/rou003:Rou/rou004:Rou/rou005&quot;
        ///    ],
        ///    &quot;BlendMode&quot;: &quot;Alpha&quot;,
        ///    &quot;Add&quot;: true,
        ///    &quot;XRangeRaw&quot;: [ &quot;472:492&quot;, &quot;501:521&quot;, &quot;529:549&quot; ],
        ///    &quot;YRangeRaw&quot;: [ &quot;8 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CandlePattern {
            get {
                return ResourceManager.GetString("CandlePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Breath&quot;: {
        ///    &quot;Prefab&quot;: &quot;Particle/pToiki&quot;,
        ///    &quot;Name&quot;: &quot;CustomEvent_Mod_Breath&quot;,
        ///    &quot;TargetBone&quot;: &quot;Bip01 Head&quot;,
        ///    &quot;Offset&quot;: {
        ///      &quot;PosString&quot;: &quot;0.04, 0.08, 0&quot;,
        ///      &quot;RotString&quot;: &quot;-90, 90, 0&quot;
        ///    }
        ///  },
        ///
        ///  &quot;SexualFluid1&quot;: {
        ///    &quot;Prefab&quot;: &quot;Particle/pPistonEasy_cm3D2&quot;,
        ///    &quot;Name&quot;: &quot;CustomEvent_Mod_SexualFluid1&quot;,
        ///    &quot;TargetBone&quot;: &quot;_IK_vagina&quot;,
        ///    &quot;Offset&quot;: {
        ///      &quot;PosString&quot;: &quot;0, 0, 0.01&quot;,
        ///      &quot;RotString&quot;: &quot;0, -180, 90&quot;
        ///    }
        ///  },
        ///
        ///  &quot;SexualFluid2&quot;: {
        ///    &quot;Prefab&quot;: &quot;Partic [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CharacterEffect {
            get {
                return ResourceManager.GetString("CharacterEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;FullBody&quot;: {
        ///    &quot;Slotname&quot;: &quot;body&quot;,
        ///    &quot;Part&quot;: &quot;&quot;,
        ///    &quot;MatNo&quot;: 0,
        ///    &quot;PropName&quot;: [
        ///      &quot;_MainTex&quot;,
        ///      &quot;_ShadowTex&quot;
        ///    ],
        ///    &quot;LayerNo&quot;: 24,
        ///    &quot;FileNameRaw&quot;: [
        ///      &quot;Lotion/lot001:Lotion/lot002&quot;,
        ///      &quot;Lotion/lot003:Lotion/lot004&quot;,
        ///      &quot;Lotion/lot001:Lotion/lot002&quot;,
        ///      &quot;Lotion/lot003:Lotion/lot004&quot;,
        ///      &quot;Lotion/lot003:Lotion/lot004&quot;,
        ///      &quot;Lotion/lot007&quot;,
        ///      &quot;Lotion/lot008&quot;,
        ///      &quot;Lotion/lot003&quot;,
        ///      &quot;Lotion/lot001&quot;,
        ///      &quot;Lotion/lot001&quot;,
        ///      &quot;Lotion/l [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LotionPattern {
            get {
                return ResourceManager.GetString("LotionPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type,FileName,NudeBodyOption,ClothedBodyOption,AdultPartOption,KidsPartOption,BodyGroup,Dummy
        ///head,mhead003_i_.menu,FALSE,FALSE,TRUE,FALSE,0,
        ///head,mhead000_i_.menu,FALSE,FALSE,TRUE,FALSE,0,
        ///head,mhead004_i_.menu,FALSE,FALSE,TRUE,FALSE,0,
        ///head,mhead002_i_.menu,FALSE,FALSE,TRUE,FALSE,0,
        ///head,mhead001_i_.menu,FALSE,FALSE,TRUE,FALSE,0,
        ///head,mhead008_i_.menu,FALSE,FALSE,FALSE,TRUE,0,
        ///head,mhead005_i_.menu,FALSE,FALSE,TRUE,FALSE,0,
        ///head,mhead006_i_.menu,FALSE,FALSE,TRUE,FALSE,0,
        ///head,mhead007_i_.menu,FAL [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ManBodyOptions {
            get {
                return ResourceManager.GetString("ManBodyOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;YoungMan&quot;: {
        ///    &quot;Head&quot;: [ &quot;mhead003_i_.menu&quot;, &quot;mhead000_i_.menu&quot;, &quot;mhead002_i_.menu&quot;, &quot;mhead001_i_.menu&quot;, &quot;mhead005_i_.menu&quot; ],
        ///    &quot;Body&quot;: [
        ///      {
        ///        &quot;Clothed&quot;: &quot;mbody_i_.menu&quot;,
        ///        &quot;Nude&quot;: &quot;mbody_i_.menu&quot;,
        ///        &quot;Min&quot;: 0,
        ///        &quot;Max&quot;: 100
        ///      },
        ///      {
        ///        &quot;Clothed&quot;: &quot;mbody002_i_.menu&quot;,
        ///        &quot;Nude&quot;: &quot;mbody001_i_.menu&quot;,
        ///        &quot;Min&quot;: 0,
        ///        &quot;Max&quot;: 50
        ///      },
        ///      {
        ///        &quot;Clothed&quot;: &quot;mbody006_i_.menu&quot;,
        ///        &quot;Nude&quot;: &quot;mbody001_i_.menu&quot;,
        ///        &quot;Mi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RandomizeManSetting {
            get {
                return ResourceManager.GetString("RandomizeManSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Vagina&quot;: {
        ///    &quot;Slotname&quot;: &quot;body&quot;,
        ///    &quot;Part&quot;: &quot;Hibu&quot;,
        ///    &quot;MatNo&quot;: 0,
        ///    &quot;PropName&quot;: [
        ///      &quot;_MainTex&quot;,
        ///      &quot;_ShadowTex&quot;
        ///    ],
        ///    &quot;LayerNo&quot;: 18,
        ///    &quot;FileNameRaw&quot;: [
        ///      &quot;Seieki/spe001:Seieki/spe002:Seieki/spe009:Seieki/spe014&quot;,
        ///      &quot;Seieki/spe001r:Seieki/spe002r:Seieki/spe009r:Seieki/spe014r&quot;,
        ///      &quot;Seieki/spe001:Seieki/spe001r:Seieki/spe002:Seieki/spe002r:Seieki/spe009:Seieki/spe009r:Seieki/spe014:Seieki/spe014r&quot;
        ///    ],
        ///    &quot;BlendMode&quot;: &quot;Alpha&quot;,
        ///    &quot;Add&quot;: true,
        ///    &quot;XRan [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SemenPattern {
            get {
                return ResourceManager.GetString("SemenPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Face&quot;: {
        ///    &quot;Slotname&quot;: &quot;head&quot;,
        ///    &quot;Part&quot;: &quot;&quot;,
        ///    &quot;MatNo&quot;: 5,
        ///    &quot;PropName&quot;: [
        ///      &quot;_MainTex&quot;,
        ///      &quot;_ShadowTex&quot;
        ///    ],
        ///    &quot;LayerNo&quot;: 13,
        ///    &quot;FileNameRaw&quot;: [
        ///      &quot;Span/span001&quot;
        ///    ],
        ///    &quot;BlendMode&quot;: &quot;Alpha&quot;,
        ///    &quot;Add&quot;: true,
        ///    &quot;XRangeRaw&quot;: [ &quot;665:689&quot; ],
        ///    &quot;YRangeRaw&quot;: [ &quot;727:757&quot; ],
        ///    &quot;RotRangeRaw&quot;: [ &quot;345:375&quot; ],
        ///    &quot;ScaleRaw&quot;: [ &quot;3.0:4.0&quot; ],
        ///    &quot;NoTransform&quot;: false,
        ///
        ///    &quot;Alpha&quot;: 1,
        ///    &quot;TargetBodyTexSize&quot;: 1024,
        ///    &quot;SplashCount&quot;: 1
        ///  },
        ///
        ///  &quot;Breast&quot;: { [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SlapMarkPattern {
            get {
                return ResourceManager.GetString("SlapMarkPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Vagina&quot;: {
        ///    &quot;Slotname&quot;: &quot;body&quot;,
        ///    &quot;Part&quot;: &quot;Hibu&quot;,
        ///    &quot;MatNo&quot;: 0,
        ///    &quot;PropName&quot;: [
        ///      &quot;_MainTex&quot;,
        ///      &quot;_ShadowTex&quot;
        ///    ],
        ///    &quot;LayerNo&quot;: 13,
        ///    &quot;FileNameRaw&quot;: [
        ///      &quot;Muchi/muchi004:Muchi/muchi005&quot;
        ///    ],
        ///    &quot;BlendMode&quot;: &quot;Alpha&quot;,
        ///    &quot;Add&quot;: true,
        ///    &quot;XRangeRaw&quot;: [ &quot;481:540&quot; ],
        ///    &quot;YRangeRaw&quot;: [ &quot;854:883&quot; ],
        ///    &quot;RotRangeRaw&quot;: [ &quot;300:420&quot; ],
        ///    &quot;ScaleRaw&quot;: [ &quot;1.0:1.0&quot; ],
        ///    &quot;NoTransform&quot;: false,
        ///
        ///    &quot;Alpha&quot;: 1,
        ///    &quot;TargetBodyTexSize&quot;: 1024,
        ///    &quot;SplashCount&quot;: 1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WhipMarkPattern {
            get {
                return ResourceManager.GetString("WhipMarkPattern", resourceCulture);
            }
        }
    }
}
